### ISSUE TITLE
fieldC: high memory usage

### ISSUE THREAD

**Issue by mlp6** [mlp6/fem#64]
Memory usage in my tests is *high*, even when running single-threaded, which usually is not a memory hog.  This memory usage also seems to grow, so this isn't something static that is preallocated.

Need to profile this is more detail.

**Comment by ndanieley** [comment]
hmmm. what inputs are you testing on?

**Comment by mlp6** [comment]
I'll put a copy on a fileserver so you can exactly replicate what I'm running.  It is running, but this config consumed >100 GB of RAM (!).  It ran... but it also doesn't appear to have saved anything.

**Comment by mlp6** [comment]
`/datacommons/ultrasound/mlp6/fieldC`

**Comment by ndanieley** [comment]
On Wed, Jul 11, 2018 at 06:24:08PM -0700, Mark Palmeri wrote:
> /datacommons/ultrasound/mlp6/fieldC

I'll need a copy of su102.json, too:

su102.json -> /dscrhome/mlp6/probes/json/su102.json

-- 
Ned Danieley (ned.danieley@duke.edu)
Department of Biomedical Engineering
Box 90281, Duke University
Durham, NC  27708   (919) 660-5111

http://dilbert.com/strips/comic/2012-02-11/

**Comment by ndanieley** [comment]
On Thu, Jul 12, 2018 at 02:23:44PM -0400, Ned Danieley wrote:
> On Wed, Jul 11, 2018 at 06:24:08PM -0700, Mark Palmeri wrote:
> > /datacommons/ultrasound/mlp6/fieldC
> 
> I'll need a copy of su102.json, too:
> 
> su102.json -> /dscrhome/mlp6/probes/json/su102.json

never mind; I went ahead and got it from the DCC. wasn't sure if I would have
access.

-- 
Ned Danieley (ned.danieley@duke.edu)
Department of Biomedical Engineering
Box 90281, Duke University
Durham, NC  27708   (919) 660-5111

http://dilbert.com/strips/comic/2012-02-11/

**Comment by ndanieley** [comment]
okay, there were two things. one was that low-n-slow was not being used at all: there was a bug in my code, which I've fixed. then, even in low-n-slow, the memory being allocated for the 'pressure' variable, which is returned by calc_hp(), was not freed after each loop. I've fixed that, and the code is only using about 300MB after running for thirty minutes. I'll see about the output problem next.

**Comment by mlp6** [comment]
Neato; did you fix the commit problem, or is git still a problem?

**Comment by ndanieley** [comment]
I still don't know quite how to fix git. I've just been pushing the fieldC part; I thought I might be able to just pull that down, but can't figure out how. I guess I could save all my stuff and just clone fem all over again, but it seems like I ought to learn how to fix this. it mostly keeps complaining about my .gitignore...

**Comment by mlp6** [comment]
If you hop on Slack, I can walk you through it on the `fem` channel.

**Comment by mlp6** [comment]
commit cf5b8796892b86046b11878e2507f75c4a8fafed
